#	$OpenBSD: Makefile,v 1.112 2024/06/30 17:30:54 deraadt Exp $

SUBDIR=	atactl badsect bioctl clri dhcp6leased dhcpleased \
	disklabel dmesg dump dumpfs fdisk fsck fsck_ext2fs fsck_ffs  \
	fsck_hammer2 fsck_msdos fsdb fsirand growfs hammer2 ifconfig iked \
	init ipsecctl isakmpd kbd ldattach mknod mount \
	mount_cd9660 mount_ext2fs mount_ffs mount_hammer2 mount_msdos \
	mount_nfs mount_ntfs mount_tmpfs mount_udf \
	mount_vnd mountd ncheck_ffs newfs newfs_ext2fs newfs_hammer2 \
	newfs_msdos nfsd nologin pdisk pfctl pflogd ping quotacheck \
	reboot resolvd restore route savecore scan_ffs \
	scsi slaacd shutdown swapctl sysctl ttyflags tunefs vnconfig \
	umount unwind wsconsctl

.include <bsd.subdir.mk>
